### ISSUE TITLE
Remove obsolete extra heroes

### ISSUE THREAD

**Issue by cvl75** [GDIBass/heroplan_data#169]
With the latest costumes added (commit #168) , I added another set of extra heroes for 2nd and 3rd costumes, which contains names (and corresponding filename) without numbers, I used 'heroname Second Costume' and 'heroname Toon Costume'. I will continue to update original 'heroname.yml' with all the costumes.
But there is the problem of the 42 extra heroes added in commit #163 that need to be deleted (and corresponding images). I could delete those files, but I don't want to break something on website. (there are 42 yaml files with filename ending in ' 2nd.yml' ; some of them contain the 3rd costume data also, so there are >42 corresponding images).
If it's ok to delete those file, please, let me know.

**Comment by GDIBass** [comment]
Yeah, it’s ok to delete but I’ll have to remove the heroes manually.

**Comment by cvl75** [comment]
Super, thanks.
