### ISSUE TITLE
Hero Images Reworking

### ISSUE THREAD

**Issue by Buffer379x** [GDIBass/heroplan_data#59]
Hey @GDIBass,

Not sure if this is the right platform since this is more for issues, but the discussion forum is not available:
I started working on creating new hero images so that the layout and color will be equal for all cards. My source is currently the newly introduced museum which shows you basically all heros that you have collected and levelled up so far (see example screenshot from in-game). From there I am using a higher resolution for editing the files which contributes in the end in a sharper image.

<img width="334" alt="Bildschirm­foto 2023-03-07 um 21 17 17" src="https://user-images.githubusercontent.com/122407181/223542844-57feea5e-fd73-41f6-907b-1975e64659ad.png">

I am bascially creating out of these screenshots the "real" in-game hero-cards with a fixed size etc. to avoid having problems with different backgrounds, face sizes, etc. (see another example from the current images)

<img width="173" alt="Bildschirm­foto 2023-03-07 um 21 21 50" src="https://user-images.githubusercontent.com/122407181/223543458-5a455d4b-47fa-4319-ba00-98d498f50127.png">

The finished file will contain all hero images in case there are problems with the existing ones so that a replacing or fixing errors will be easier in the future (at the moment, you would have to create a new card since we are not saving the project file, just the exported images).

<img width="269" alt="Bildschirm­foto 2023-03-07 um 21 13 04" src="https://user-images.githubusercontent.com/122407181/223543797-0f46b7a4-afd2-4c6c-b989-5684e7a74f93.png">

**My question is the following:**
The current images have a layer on top with the LVL info, a black bar as well as the ascension level / limit break. Is this something that is being added afterwards dynamically again since there are separate files for it? Or is this something which I should consider adding also on top of the new images?

I am attaching you example exports to see if that might work for you. Also, I am not changing any hero files yet until all it is clear that it will cause no problems and the first big set of images will be ready.

![domitiacostume1](https://user-images.githubusercontent.com/122407181/223544866-f132d3d0-e2a3-4af4-ad52-6277149d362b.png)
![guardiankong](https://user-images.githubusercontent.com/122407181/223544869-c4d60b2f-6eac-47c7-8266-02eca7de193a.png)
![Ludwig](https://user-images.githubusercontent.com/122407181/223544873-e35e1d65-b225-40be-92fb-a09b5690dcf1.png)

Greetings

**Comment by GDIBass** [comment]
The level info and bars are added afterwards, although not the black bar.  That should be easy-ish to add though.

question, does the hero museum have similar functionality to hero plan?  Is it going to replace it eventually?

**Comment by Buffer379x** [comment]
> question, does the hero museum have similar functionality to hero plan? Is it going to replace it eventually?

Never 😁

Basically it contains all heroes, they are just hidden. Once you pull the hero, they become a grey image. And if you level it to max they show up as the small icon version and you get x diamonds. Thats all. No statistics, no planning, no filtering. It is plain for collection / diamond purposes.

**Comment by Buffer379x** [comment]
Will most probably not work as expected. The images have a different zoom factor of the heroes which blocks the bottom part once the black layer is added. Theoretically the tournament / raid images can be used, but they on the other hand contain the emblem level already as well as the family symbols. And to erase those just to add them afterwards dynamically is way too much (unnecessary) work...

Need to think of a different approach.

<img width="110" alt="Bildschirm­foto 2023-03-08 um 08 09 57" src="https://user-images.githubusercontent.com/122407181/223645214-e785d344-09b5-4e44-b78b-d07cf426bddf.png">
<img width="110" alt="Bildschirm­foto 2023-03-08 um 08 11 02" src="https://user-images.githubusercontent.com/122407181/223645232-9eb94f8f-411b-4c77-bcc3-7ef2249b9449.png">
