### ISSUE TITLE
Last heroes added shows default images on heroplan.io

### ISSUE THREAD

**Issue by cvl75** [GDIBass/heroplan_data#77]
Hello,
Since I added the last HotM, Turluk, the heroes images are generic ones. 
Even more, for Turluk the default image is purple, but for all the costumes is gray.

**Comment by GDIBass** [comment]
It’s probably something messed up with the cache being cleared.  I’ll take a look tonight.

**Comment by GDIBass** [comment]
Looks like it's updated now.  I think it was a cacheing issues

**Comment by GDIBass** [comment]
I'm gonna set up some automated cache clears to fix things automatically next time.  Let me know if you see this agin.

**Comment by cvl75** [comment]
Super.
Will do.
